# Generated by Django 5.2 on 2025-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='Book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
